'use client';

import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { personalizedWelcomeText, PersonalizedWelcomeTextInput } from '@/ai/flows/personalized-welcome-text';
import { Loader2 } from 'lucide-react';

export default function PersonalizationTool() {
  const [interest, setInterest] = useState('projects');
  const [welcomeText, setWelcomeText] = useState(
    "Welcome! I'm Raj Kumar. Select an interest below to get a personalized greeting."
  );
  const [loading, setLoading] = useState(false);

  const handleInterestChange = async (value: string) => {
    setInterest(value);
    setLoading(true);
    try {
      const input: PersonalizedWelcomeTextInput = { visitorInterest: value };
      const result = await personalizedWelcomeText(input);
      setWelcomeText(result.welcomeText);
    } catch (error) {
      console.error('Error generating personalized text:', error);
      setWelcomeText('Sorry, I couldn\'t generate a personalized message right now. Please explore my projects below!');
    } finally {
      setLoading(false);
    }
  };

  return (
    <section id="personalize" className="w-full py-12 md:py-24 bg-muted/40">
      <div className="container mx-auto px-4 md:px-6">
        <div className="grid gap-10 lg:grid-cols-5">
            <div className="lg:col-span-2 space-y-4">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl font-headline">AI-Powered Greeting</h2>
                <p className="text-muted-foreground">
                    This portfolio uses a touch of AI. Let me know what you&apos;re here for, and I&apos;ll generate a custom welcome message for you!
                </p>
                <RadioGroup value={interest} onValueChange={handleInterestChange} className="space-y-2">
                    <div className="flex items-center space-x-2">
                        <RadioGroupItem value="projects" id="r1" />
                        <Label htmlFor="r1">My Projects</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                        <RadioGroupItem value="skills" id="r2" />
                        <Label htmlFor="r2">My Skills</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                        <RadioGroupItem value="contact" id="r3" />
                        <Label htmlFor="r3">Contacting Me</Label>
                    </div>
                </RadioGroup>
            </div>
            <div className="lg:col-span-3">
                <Card className="h-full border-2 border-primary/50 shadow-lg bg-card/80">
                    <CardHeader>
                        <CardTitle>A Message For You</CardTitle>
                        <CardDescription>Generated by a custom AI model.</CardDescription>
                    </CardHeader>
                    <CardContent className="flex items-center justify-center min-h-[100px]">
                        {loading ? (
                            <Loader2 className="h-8 w-8 animate-spin text-primary" />
                        ) : (
                            <p className="text-lg text-center text-foreground">{welcomeText}</p>
                        )}
                    </CardContent>
                </Card>
            </div>
        </div>
      </div>
    </section>
  );
}
